# Berlin Bites Sentiment Analysis

This notebook loads the **translated dataset** downloaded from the Opentable API

In [1]:
import pandas as pd
import os
import ast

## 1. Load Raw Data

In [10]:
from pathlib import Path

path = Path("../data/raw/SeoulBikeData.csv")

In [11]:
df = pd.read_csv(path)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 40: invalid start byte

## 2. Cleaning Data

In [88]:
df.head()

,id,content,dined_at,submitted_at,user,rating,restaurant_id,response,content_needs_translation,response_needs_translation,content_translated,response_translated,content_translated_more_translation,response_translated_more_translation
0,OT-128943-38108-160080614146,味に関してはご飯が乾燥していて美味しくなかったです。またそのご飯に黒胡麻が多すぎてジャリジャ...,2018-08-15T11:30:00Z,2018-08-17T15:28:54Z,"{'name': 'YOICHI', 'number_of_reviews': 2, 'lo...","{'overall': 4, 'food': 3, 'service': 4, 'ambie...",r/sticksnsushi-potsdamer-berlin,NaN,True,False,"Regarding the taste, the rice was dry and not ...",NaN,False,False
1,OT-350100-50258-390086046109,"tolle raffinierte Gerichte, toller Service und...",2026-05-09T17:30:00Z,2026-05-11T15:40:56Z,"{'name': 'Marcus', 'number_of_reviews': 3, 'lo...","{'overall': 5, 'food': 5, 'service': 5, 'ambie...",r/sticksnsushi-potsdamer-berlin,{'content': 'Vielen Dank für Ihr schönes Feedb...,True,True,"great refined dishes, great service and good v...",{'content': 'Thank you for your nice feedback....,False,False
2,OT-350100-50019-380058082468,Ein schöner Abend mit lieben Freunden an einem...,2026-05-04T17:00:00Z,2026-05-05T22:07:00Z,"{'name': 'Gerd', 'number_of_reviews': 4, 'loca...","{'overall': 4, 'food': 5, 'service': 3, 'ambie...",r/sticksnsushi-potsdamer-berlin,"{'content': 'Lieber Gerd,\n\nvielen Dank für d...",True,True,A lovely evening with dear friends at one of t...,"{'content': 'Dear Gerd,\n\nThank you for the k...",False,False
3,OT-350100-50085-150051028935,"Outstanding food, lovely and always excellent ...",2026-05-03T18:30:00Z,2026-05-04T11:14:35Z,"{'name': 'Pierre', 'number_of_reviews': 11, 'l...","{'overall': 5, 'food': 5, 'service': 5, 'ambie...",r/sticksnsushi-potsdamer-berlin,"{'content': ""Lovely Pierre,\nThank you very mu...",False,False,"Outstanding food, lovely and always excellent ...","{'content': ""Lovely Pierre,\nThank you very mu...",False,False
4,OT-350100-49921-170027724967,Unfortunately we didn’t get to dine there on 1...,2026-05-01T20:00:00Z,2026-05-14T12:41:15Z,"{'name': 'Michael', 'number_of_reviews': 1, 'l...","{'overall': 5, 'food': 4, 'service': 4, 'ambie...",r/sticksnsushi-potsdamer-berlin,NaN,False,False,Unfortunately we didn’t get to dine there on 1...,NaN,False,False

In [89]:
df.head()

,id,content,dined_at,submitted_at,user,rating,restaurant_id,response,content_needs_translation,response_needs_translation,content_translated,response_translated,content_translated_more_translation,response_translated_more_translation
0,OT-128943-38108-160080614146,味に関してはご飯が乾燥していて美味しくなかったです。またそのご飯に黒胡麻が多すぎてジャリジャ...,2018-08-15T11:30:00Z,2018-08-17T15:28:54Z,"{'name': 'YOICHI', 'number_of_reviews': 2, 'lo...","{'overall': 4, 'food': 3, 'service': 4, 'ambie...",r/sticksnsushi-potsdamer-berlin,NaN,True,False,"Regarding the taste, the rice was dry and not ...",NaN,False,False
1,OT-350100-50258-390086046109,"tolle raffinierte Gerichte, toller Service und...",2026-05-09T17:30:00Z,2026-05-11T15:40:56Z,"{'name': 'Marcus', 'number_of_reviews': 3, 'lo...","{'overall': 5, 'food': 5, 'service': 5, 'ambie...",r/sticksnsushi-potsdamer-berlin,{'content': 'Vielen Dank für Ihr schönes Feedb...,True,True,"great refined dishes, great service and good v...",{'content': 'Thank you for your nice feedback....,False,False
2,OT-350100-50019-380058082468,Ein schöner Abend mit lieben Freunden an einem...,2026-05-04T17:00:00Z,2026-05-05T22:07:00Z,"{'name': 'Gerd', 'number_of_reviews': 4, 'loca...","{'overall': 4, 'food': 5, 'service': 3, 'ambie...",r/sticksnsushi-potsdamer-berlin,"{'content': 'Lieber Gerd,\n\nvielen Dank für d...",True,True,A lovely evening with dear friends at one of t...,"{'content': 'Dear Gerd,\n\nThank you for the k...",False,False
3,OT-350100-50085-150051028935,"Outstanding food, lovely and always excellent ...",2026-05-03T18:30:00Z,2026-05-04T11:14:35Z,"{'name': 'Pierre', 'number_of_reviews': 11, 'l...","{'overall': 5, 'food': 5, 'service': 5, 'ambie...",r/sticksnsushi-potsdamer-berlin,"{'content': ""Lovely Pierre,\nThank you very mu...",False,False,"Outstanding food, lovely and always excellent ...","{'content': ""Lovely Pierre,\nThank you very mu...",False,False
4,OT-350100-49921-170027724967,Unfortunately we didn’t get to dine there on 1...,2026-05-01T20:00:00Z,2026-05-14T12:41:15Z,"{'name': 'Michael', 'number_of_reviews': 1, 'l...","{'overall': 5, 'food': 4, 'service': 4, 'ambie...",r/sticksnsushi-potsdamer-berlin,NaN,False,False,Unfortunately we didn’t get to dine there on 1...,NaN,False,False

In [90]:
# Convert object column to datetime
df["dined_at"] = pd.to_datetime(df["dined_at"])

# Create separate columns
df["date_dined"] = df["dined_at"].dt.date
df["time_dined"] = df["dined_at"].dt.time

In [91]:
# Convert object column to datetime
df["submitted_at"] = pd.to_datetime(df["submitted_at"])

# Create separate columns
df["date_submitted"] = df["submitted_at"].dt.date
df["time_submitted"] = df["submitted_at"].dt.time

In [92]:
df.loc[0]['user']

"{'name': 'YOICHI', 'number_of_reviews': 2, 'location': 'ロンドン'}"

In [93]:
df.loc[0]['rating']

"{'overall': 4, 'food': 3, 'service': 4, 'ambience': 4, 'value': 2, 'noise': 'Do Not Recall'}"

In [94]:
df.loc[0]['restaurant_id']

'r/sticksnsushi-potsdamer-berlin'

In [95]:
def expand_dict_column(df, column_name, prefix=None):
    # Convert string dictionaries to real dictionaries
    parsed = df[column_name].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    # Expand into columns
    expanded = parsed.apply(pd.Series)
    # Optional prefix
    if prefix:
        expanded = expanded.add_prefix(prefix)

    return pd.concat([df, expanded], axis=1)

In [96]:
df = expand_dict_column(df, "user", prefix="user_")
df = expand_dict_column(df, "rating", prefix="rating_")

In [97]:
df['restaurant_id'] = df['restaurant_id'].str.split('/').str[-1]

## 3. Dealing with Null Values

In [ ]:
df.isna().sum()

id                                         0
content                                    0
dined_at                                   0
submitted_at                               0
user                                       0
rating                                     0
restaurant_id                              0
response                                 990
content_needs_translation                  0
response_needs_translation                 0
content_translated                         0
response_translated                      990
content_translated_more_translation        0
response_translated_more_translation       0
date_dined                                 0
time_dined                                 0
date_submitted                             0
time_submitted                             0
user_name                                100
user_number_of_reviews                     0
user_location                              0
user_avatar                             1230
user_vip                                1270
rating_overall                             0
rating_food                                0
rating_service                             0
rating_ambience                            0
rating_value                               0
rating_noise                               0
dtype: int64

In [99]:
df = df.drop(columns=["content", "response", 'content_needs_translation', 'response_needs_translation', 'content_translated_more_translation',
                      'response_translated_more_translation', 'dined_at', 'submitted_at','user', 'rating', 'response_translated', 'user_avatar', 'user_vip'])

In [100]:
df.head()

,id,restaurant_id,content_translated,date_dined,time_dined,date_submitted,time_submitted,user_name,user_number_of_reviews,user_location,rating_overall,rating_food,rating_service,rating_ambience,rating_value,rating_noise
0,OT-128943-38108-160080614146,sticksnsushi-potsdamer-berlin,"Regarding the taste, the rice was dry and not ...",2018-08-15,11:30:00,2018-08-17,15:28:54,YOICHI,2,ロンドン,4,3,4,4,2,Do Not Recall
1,OT-350100-50258-390086046109,sticksnsushi-potsdamer-berlin,"great refined dishes, great service and good v...",2026-05-09,17:30:00,2026-05-11,15:40:56,Marcus,3,ノルトライン＝ヴェストファーレ,5,5,5,5,4,Energetic
2,OT-350100-50019-380058082468,sticksnsushi-potsdamer-berlin,A lovely evening with dear friends at one of t...,2026-05-04,17:00:00,2026-05-05,22:07:00,Gerd,4,ベルリン,4,5,3,4,3,Energetic
3,OT-350100-50085-150051028935,sticksnsushi-potsdamer-berlin,"Outstanding food, lovely and always excellent ...",2026-05-03,18:30:00,2026-05-04,11:14:35,Pierre,11,ベルリン,5,5,5,5,5,Do Not Recall
4,OT-350100-49921-170027724967,sticksnsushi-potsdamer-berlin,Unfortunately we didn’t get to dine there on 1...,2026-05-01,20:00:00,2026-05-14,12:41:15,Michael,1,サンフランシスコ・ベイ周辺,5,4,4,4,4,Do Not Recall

In [105]:
df['user_location'].unique()

array(['ロンドン', 'ノルトライン＝ヴェストファーレ', 'ベルリン', 'サンフランシスコ・ベイ周辺', 'バイエルン州',
       'シュトゥットガルト', 'Berlin', 'SH', 'Hamburg', 'Sachsen', 'Raum New York',
       'Las Vegas', '東京', 'ハンブルク', 'New York', 'Hambourg', 'Austin',
       'Dublin', 'Glasgow', 'Grand Boston', '柏林', 'New York City',
       'Mexico City', '杜塞尔多夫', 'London', '科隆', 'MV', 'Munich',
       'San Francisco', 'Dubai', 'Seattle', 'Cornwall', 'Londres',
       'Amburgo', 'Düsseldorf', 'Berlino', 'Washington DC', 'Detroit',
       'Bassa Sassonia', 'Sassonia', 'Berlín', 'Stuttgart', 'Brandenburg',
       'Nueva York', 'Hungary', '梅克伦堡-前波美拉尼亚', '汉堡', 'Keulen',
       'Nedersaksen', 'Washington, D.C', 'Mexico-Stad', 'Los Angeles',
       'Berlijn', 'Lower Saxony', 'BW', 'San Diego'], dtype=object)

In [106]:
df['restaurant_id'].unique()

array(['sticksnsushi-potsdamer-berlin', 'vox-restaurant-berlin',
       'neni-berlin', 'katz-orange', 'peterpaul-berlin',
       'cafe-wintergarten-berlin', 'maison-papillon-berlin',
       'kink-bar-and-restaurant-berlin', 'wilde-matilde-berlin',
       'anna-and-paul-berlin', 'miyaki-japan-meets-persia-berlin',
       'the-alchemist-bar-and-restaurant-berlin',
       'pizzeria-mario-x-gambino-berlin'], dtype=object)

## 4. Data Translation ???

## 5. Export to CSV

In [ ]:
output_dir = "data/processed"
os.makedirs(output_dir, exist_ok=True)

df.to_csv(f"{output_dir}/reviews.csv", index=False)

print("Exported:")
for f in os.listdir(output_dir):
    path = os.path.join(output_dir, f)
    size = os.path.getsize(path)
    print(f"  {f} ({size:,} bytes)")

Exported:
  reviews.csv (1,400,846 bytes)